services:
  db:
    container_name: postgres_mpp
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mpp
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5431:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
