name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build Frontend
        working-directory: ./student-management-frontend
        run: |
          npm ci
          npm run build

      - name: Build Backend
        working-directory: ./studentmanagement
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Deploy Frontend
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_BOTH }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY_BOTH }}
          source: "student-management-frontend/dist/**"
          target: "/var/www/html"

      - name: Deploy Backend JAR
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_BOTH }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY_BOTH }}
          source: "studentmanagement/target/*.jar"
          target: "/home/ec2-user/app"

      - name: Restart Backend
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_BOTH }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY_BOTH }}
          script: |
            pkill -f 'java -jar' || true
            sleep 2
            cd /home/ec2-user/app/studentmanagement/target
            nohup java -jar studentmanagement-0.0.1-SNAPSHOT.jar > backend.log 2>&1 &
            sleep 3
            pgrep -f 'java -jar' || echo "Failed to start backend"
